language: node_js
node_js:
  - 13
env:
  - APP_VERSION=0.0.1 DOCKER_REPO=simple-node

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t $DOCKER_REPO .
  - docker tag $DOCKER_REPO $DOCKER_USERNAME/$DOCKER_REPO:$APP_VERSION

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo $DOCKER_USERNAME
  - echo $DOCKER_REPO
  - docker push $DOCKER_USERNAME/$DOCKER_REPO:$APP_VERSION
