language: node_js
node_js:
  - 13
env:
  - APP_VERSION=0.0.1 DOCKER_REPO=env-var-travis NAME=MYfavINSTRUCTOR

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - make image 
  - make tag

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PERSONAL_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/$DOCKER_REPO:$APP_VERSION
